import Foundation

/// Safe resolver for CodexBarCore's SwiftPM resource bundle.
///
/// The autogenerated `Bundle.module` accessor traps at launch when the packaged
/// app does not place `CodexBar_CodexBarCore.bundle` at the locations it probes
/// (the app root and the compile-time build directory). The packaged app ships
/// the bundle in `Contents/Resources`, so anchor app lookup to the resolved executable.
/// Development builds open their known bundle directly without invoking a trapping accessor.
/// Shipped command-line tools also resolve the bundle beside the
/// executable; a missing bundle is reported by callers instead of trapping.
public enum CodexBarCoreResources {
    static let missingBundleMessage =
        "CodexBarCore resource bundle is missing next to the executable; reinstall or update CodexBar"

    public static let bundle: Bundle? = resolve(mainBundle: .main)

    static func resolve(
        mainBundle: Bundle,
        executableURL: URL? = nil,
        swiftPMBuildDirectory: URL? = Self.defaultSwiftPMBuildDirectory) -> Bundle?
    {
        let name = "CodexBar_CodexBarCore"
        let bundleName = "\(name).bundle"
        let swiftPMBundleNames = [bundleName, "\(name).resources"]

        guard let executable = (executableURL ?? ExecutableLocation.runningURL(bundle: mainBundle))?
            .resolvingSymlinksInPath() else { return nil }
        if let appURL = ExecutableLocation.appBundleURL(containing: executable),
           let appBundle = Bundle(url: appURL)
        {
            if let url = appBundle.url(forResource: name, withExtension: "bundle"),
               let bundle = Bundle(url: url)
            {
                return bundle
            }
            if let resourceURL = appBundle.resourceURL,
               let bundle = Bundle(url: resourceURL.appendingPathComponent(bundleName))
            {
                return bundle
            }
            if let bundle = Bundle(url: appURL.appendingPathComponent(bundleName)) {
                return bundle
            }
        }

        let executableDirectory = executable.deletingLastPathComponent()
        for swiftPMBundleName in swiftPMBundleNames {
            let executableCandidate = executableDirectory.appendingPathComponent(swiftPMBundleName)
            if let bundle = Bundle(url: executableCandidate) {
                return bundle
            }
        }

        if let swiftPMBuildDirectory {
            for buildBundleName in swiftPMBundleNames {
                if let bundle = Bundle(url: swiftPMBuildDirectory.appendingPathComponent(buildBundleName)) {
                    return bundle
                }
            }
        }
        return nil
    }

    private static let defaultSwiftPMBuildDirectory: URL = {
        let packageRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent() // CodexBarCore
            .deletingLastPathComponent() // Sources
            .deletingLastPathComponent() // package root
        #if DEBUG
        let configuration = "debug"
        #else
        let configuration = "release"
        #endif
        return packageRoot.appendingPathComponent(".build/\(configuration)", isDirectory: true)
    }()
}
